<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\src\MedicalAssistant.Api\MedicalAssistant.Api.csproj" />
    <ProjectReference Include="..\..\AI\src\MedicalAssistance.Ingestion.Api\MedicalAssistance.Ingestion.Api.csproj"
                      ReferenceOutputAssembly="false"
                      SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="..\..\backend\src\MedicalAssistant.Transcription.Worker\MedicalAssistant.Transcription.Worker.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
