export const queryKeys = {
  session: ["auth", "session"] as const,
  patient: (id: number) => ["patient", id] as const,
  patients: ["patients"] as const,
  patientHistory: (
    id: number,
    fromDate?: string,
    toDate?: string,
    page?: number,
    pageSize?: number,
    source?: string,
  ) =>
    [
      "patient",
      id,
      "history",
      fromDate ?? null,
      toDate ?? null,
      page ?? null,
      pageSize ?? null,
      source ?? null,
    ] as const,
  patientHistoryPrefix: (id: number) => ["patient", id, "history"] as const,
  consultationsByPatient: (patientId: number) => ["patient", patientId, "consultations"] as const,
  draftConsultations: ["consultations", "drafts"] as const,
  unattachedDraftConsultations: ["consultations", "drafts", "unattached"] as const,
  dashboardAnalytics: ["consultations", "analytics"] as const,
  consultation: (id: number) => ["consultation", id] as const,
  consultationAudio: (id: number) => ["consultation", id, "audio"] as const,
  transcript: (consultationId: number) => ["consultation", consultationId, "transcript"] as const,
  structuredData: (consultationId: number) => ["consultation", consultationId, "structured-data"] as const,
  doctorNotes: (consultationId: number) => ["consultation", consultationId, "doctor-notes"] as const,
  patientDoctorNotes: (patientId: number) => ["patient", patientId, "doctor-notes"] as const,
  action: (correlationId: string) => ["action", correlationId] as const,
  conversations: (patientId: number) => ["patient", patientId, "conversations"] as const,
  conversationThread: (conversationId: number) => ["conversation", conversationId, "thread"] as const,
};
