export const queryKeys = {
  session: (userId: string) => ["auth", "session", userId] as const,
  patient: (id: number) => ["patient", id] as const,
  patients: ["patients"] as const,
  patientHistory: (
    id: number,
    fromDate?: string,
    toDate?: string,
    page?: number,
    pageSize?: number,
    source?: string,
  ) =>
    [
      "patient",
      id,
      "history",
      fromDate ?? null,
      toDate ?? null,
      page ?? null,
      pageSize ?? null,
      source ?? null,
    ] as const,
  patientHistoryPrefix: (id: number) => ["patient", id, "history"] as const,
  consultationsByPatient: (patientId: number) => ["patient", patientId, "consultations"] as const,
  draftConsultations: ["consultations", "drafts"] as const,
  unattachedDraftConsultations: ["consultations", "drafts", "unattached"] as const,
  dashboardAnalytics: ["consultations", "analytics"] as const,
  consultation: (id: number) => ["consultation", id] as const,
  consultationAudio: (id: number) => ["consultation", id, "audio"] as const,
  transcript: (consultationId: number) => ["consultation", consultationId, "transcript"] as const,
  structuredData: (consultationId: number) => ["consultation", consultationId, "structured-data"] as const,
  doctorNotes: (consultationId: number) => ["consultation", consultationId, "doctor-notes"] as const,
  patientDoctorNotes: (patientId: number) => ["patient", patientId, "doctor-notes"] as const,
  chat: (correlationId: string) => ["chat", correlationId] as const,
  users: (page: number, pageSize: number) => ['users', page, pageSize] as const,
  usersPrefix: ['users'] as const,
  auditLogs: (page: number, pageSize: number) => ['logs', 'audit', page, pageSize] as const,
  errorLogs: (page: number, pageSize: number) => ['logs', 'errors', page, pageSize] as const,
};
