// <auto-generated />
using System;
using MedicalAssistance.Ingestion.Api.Ingestions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MedicalAssistance.Ingestion.Api.Ingestions.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20260719140541_DocumentIdCarriesDoctorAndPatient")]
    partial class DocumentIdCarriesDoctorAndPatient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalAssistance.Ingestion.Api.Ingestions.AgentInstruction", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Name");

                    b.ToTable("agent_instructions", (string)null);
                });

            modelBuilder.Entity("MedicalAssistance.Ingestion.Api.Ingestions.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_kind");

                    b.Property<string>("ContextBlurb")
                        .HasColumnType("text")
                        .HasColumnName("context_blurb");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_id");

                    b.Property<DateTimeOffset?>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(3072)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceRef")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_ref");

                    b.Property<string>("VerbatimText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verbatim_text");

                    b.HasKey("Id");

                    b.HasIndex("IngestionId");

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("MedicalAssistance.Ingestion.Api.Ingestions.IngestionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("ChatModel")
                        .HasColumnType("text")
                        .HasColumnName("chat_model");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_id");

                    b.Property<DateTimeOffset?>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("InstructionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("instruction_version");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "Status");

                    b.HasIndex("SessionId", "SequenceNumber", "ContentHash");

                    b.ToTable("ingestions", (string)null);
                });

            modelBuilder.Entity("MedicalAssistance.Ingestion.Api.Ingestions.Chunk", b =>
                {
                    b.HasOne("MedicalAssistance.Ingestion.Api.Ingestions.IngestionRecord", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
